samples: thrift: hello: limit integration platforms to working
With a recent update to thrift, the `uart_pipe` does not seem
to compile anymore.

```
drivers/serial/uart_pipe.c: In function 'uart_pipe_register':
/home/cfriedt/my-workspace/zephyr/include/zephyr/device.h:96:39: error: '__device_dts_ord_DT_CHOSEN_zephyr_uart_pipe_ORD' undeclared (first use in this function)
   96 | #define DEVICE_NAME_GET(name) _CONCAT(__device_, name)
```

Limit integration platforms to known working ones.

Signed-off-by: Christopher Friedt <cfriedt@fb.com>